### ISSUE TITLE
Exception in Application start method

### ISSUE THREAD

**Issue by rahmanusta** [gluonhq/client-samples#12]
Hello,

I created native image on Mac for the https://github.com/javaterminal/TerminalFX project. It successfully created TerminalFX.app, but when it started it is giving me the 'Exception in Application start method' error. How can I see the exception details?

```
[DEBUG] Start running in /Users/usta/projects/TerminalFX/target/client
Omega :: host triplet = x86_64-macos-macos
Omega :: target triplet = x86_64-macos-macos
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] 2019-07-01 14:00:48.097 TerminalFX[1755:29623] Starting Gluon VM...
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] 2019-07-01 14:00:48.097 TerminalFX[1755:29623] Starting Gluon VM...
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] InitializeEncoding is now (lazily) called
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] InitializeEncoding is now (lazily) called
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] ONLOAD PRISM_ES2
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] ONLOAD PRISM_ES2
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] Exception in Application start method
[Mon Jul 01 14:00:48 EET 2019][INFO] [SUB] Exception in Application start method
```

Thanks
Rahman

**Comment by jperedadnr** [comment]
You can track any exception in the start method just by adding a `try - catch` with a throwable, like:

```
@Override
    public void start(Stage stage) throws Exception {
        try {
            InputStream sceneStream = TerminalAppStarter.class.getResourceAsStream("/fxml/Terminal_Scene.fxml");
            ...
            stage.show();
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    public static void main(String[] args) {
        try {
            launch(args);
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
```

Thanks to the stack traces, I've managed to build the app and find some classes that were being called reflectively and were not part of the built in reflection list. Therefore you have to add them to the reflection list, like:

```
<reflectionList>
            <list>javafx.fxml.FXMLLoader</list>
            <list>com.kodedu.terminalfx.FXMLController</list>
            <list>javafx.scene.control.TabPane</list>
            <list>javafx.scene.control.TabPane$TabClosingPolicy</list>
            <list>javafx.scene.layout.Priority</list>
            <list>javafx.scene.web.WebView</list>
            <list>javafx.scene.web.WebEngine</list>
        </reflectionList>
```

The bad news at this point is now related to this issue: https://github.com/gluonhq/client-maven-plugin/issues/28, both Media and Web modules are not supported yet (there are no static libraries for these modules yet), and I get:

> java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path

**Comment by rahmanusta** [comment]
Thanks @jperedadnr , I was planning to release my JavaFX projects with native image, but the media and web limitation blocks it now :) I'm gonna chase the https://github.com/gluonhq/client-maven-plugin/issues/28 issue.
