### ISSUE TITLE
Something happened when execute nativeCompile

### ISSUE THREAD

**Issue by MakHoCheung** [gluonhq/client-samples#18]
![image](https://user-images.githubusercontent.com/22256775/63007866-122f6f00-beb4-11e9-80c1-26774ec69ae9.png)
Just a "hello world" app. It spent long time. Will the nativeCompile download somthing?

**Comment by jperedadnr** [comment]
If you see the documentation, native compile takes usually more than 5 minutes, depending on your machine. It doesn't download anything in the process, other than the necessary dependencies.
