### ISSUE TITLE
Will performance on Android improve due to GraalVM..?

### ISSUE THREAD

**Issue by shoeoffhead** [gluonhq/client-samples#22]
Hi,

I did compile and test about half of the Gluon samples on older Android devices: https://gluonhq.com/developers/samples

Those devices run a current version of Android (7.1 and 8.1) and run other apps like Chrome, Instagram & Twitter very quickly. Fast startup. Basically no lag. 

With the Gluon samples I have very long startup times even if the device is IDLE. Even worse the UI feels very sluggish due to a lot of very noticeable lag. This is no fun.

I hoped the "**Gluon Mobile with Gluon VM**" samples would improve things. Sadly they don't.

What is the technical reason the startup time is so long and the UI so very sluggish with Gluon apps? Am I the first person to bring this up? Even on my flashship smartphone (S10) I feel a little lag with Gluon apps. Hardly noticeable but it is there. No so with any other app on my S10. Given that most people have much slower Android devices performance seems to be the #1 issue for Gluon to go forward?

Will the use of GraalVM improve on this?

**Comment by Hugolarson** [comment]
Me too wonder what GraalVM will bring to Android platform.
Do you use ART or Dalvik?

**Comment by johanvos** [comment]
By using GraalVM, we don't use ART nor Dalvik, GraalVM native-image compiles the Java bytecode into native code (for AArch64). We then simply execute that native code, so it directly runs on the underlying (linux-based) system, without any Dalvik/ART in between.

**Comment by shoeoffhead** [comment]
Thanks @johanvos 
Can you please also comment on my initial post? Am I imagining this or is performance (without GraalVM) really that bad? I just compare it to standard native (meaning using only Google-API for UI and everything) Android apps. Those apps are really snappy. The Gluon Mobile with Gluon VM samples are not.

Is there a technical reason why they are so slow?

I assume GraalVM will make Gluon Mobile sample or client-samples faster. But will they be really comparable in speed to native apps? My instinct is, that there is something problematic when it comes to performance (startup, UI snappiness, etc.) with the current technical approach and GraalVM compilation will help it a little bit but cannot save the day performance-wise.

Maybe I am wrong and I am happy if you correct my experience in my initial post, since the performance was shockingly bad. Maybe you can offer APKs of samples that have better performance (with or without GraalVM compilation) - I would love to test them out.

**Comment by Hugolarson** [comment]
@johanvos 
This is fascinating.
Running directly on Android Linux based system mean there is no limitation of Android API level I guess.

**Comment by dragetd** [comment]
No, native code still has strict limitations by Android… it cannot get any elevated permissions compared to plain Java bytecode applications.

**Comment by johanvos** [comment]
Any code is still subject to the permissions of the kernel. But I think the question is about Android API levels, which are irrelevant since we don't use the Android API's anymore.

**Comment by johanvos** [comment]
> Thanks @johanvos
> Can you please also comment on my initial post? Am I imagining this or is performance (without GraalVM) really that bad? I just compare it to standard native (meaning using only Google-API for UI and everything) Android apps. Those apps are really snappy. The Gluon Mobile with Gluon VM samples are not.
> 
> Is there a technical reason why they are so slow?
> 
> I assume GraalVM will make Gluon Mobile sample or client-samples faster. But will they be really comparable in speed to native apps? My instinct is, that there is something problematic when it comes to performance (startup, UI snappiness, etc.) with the current technical approach and GraalVM compilation will help it a little bit but cannot save the day performance-wise.
> 
> Maybe I am wrong and I am happy if you correct my experience in my initial post, since the performance was shockingly bad. Maybe you can offer APKs of samples that have better performance (with or without GraalVM compilation) - I would love to test them out.

Apart from simple native performance, we need to work on some of the implementations of the UI controls, including the virtual flow (making improvements to e.g. swipe event handling). But in general.

**Comment by Hugolarson** [comment]
This sounds like there are many restrictions running graal compiled to native code on Android? 
What does this translate to on real world applications which need access to hardware such as network?

**Comment by dragetd** [comment]
Not being an Android expert, but I am fairly certain: You do not have more or less restrictions when running as native code. Native libs *can* access all the things JVM Bytecode can access, if granted the correct permissions. (The Android API is not available for making these calls, but there are supplements.)

As far as I understood, the whole stack is actually only possible like this by using GraalVM native-image, so this is something we 'want'. :-)

The question about performance is a bit tricky. The JavaFX code is not reimplemented by the Gluon project, but only configured and compiled to the right target platforms. It might 'automagically' improve the performance when JavaFX or GraalVM develops further. A good way to 'help' the project is actually to use it and build simple examples and try running them through all the steps, maybe using different versions of the JDKs and JavaFX. And if you find an issue, report it. A robust platform is also easier to optimize.

**Comment by jperedadnr** [comment]
Closing this issue now. If still relevant, feel free to reopen.
