### ISSUE TITLE
When will windows support be release?

### ISSUE THREAD

**Issue by ZhenFTW** [gluonhq/client-samples#23]
I know it might be annoying asking this question over and over but i really am looking forward to try this on windows

**Comment by bgmf** [comment]
There is yet no official support for the GraalVM CE on Window by Oracle itself. I guess Gluon will only be able to provide Windows binaries, if Oracle's dev team officially support them.

**Comment by jperedadnr** [comment]
GraalVM 19.3 for Java 11 has just been released, and includes Windows support. 

Based on this release, and as a heads up, `HelloWorld` runs on Windows (see [PR](https://github.com/gluonhq/substrate/pull/100)) with the current plugin. It is still under development and there is no documentation yet, but it will be there soon.

**Comment by iw-an** [comment]
> GraalVM 19.3 for Java 11 has just been released, and includes Windows support.
> 
> Based on this release, and as a heads up, `HelloWorld` runs on Windows (see [PR](https://github.com/gluonhq/substrate/pull/100)) with the current plugin. It is still under development and there is no documentation yet, but it will be there soon.

Using the current plugin on Windows 10, it errors out with the following `Execution default-cli of goal com.gluonhq:client-maven-plugin:0.1.3:compile failed: OS windows 10 not supported`

**Comment by Hugolarson** [comment]
Can we dream of GraalVM will work with Swing also?

**Comment by tsatatwer** [comment]
We are still dreaming of GraalVM work with JavaFX on windows ????????? .

**Comment by tiainen** [comment]
Just a quick update on support for JavaFX on Windows. We are stuck in a difficult to pin down issue and are waiting for this GraalVM issue to be fixed: https://github.com/oracle/graal/issues/2101. That would aid us a lot in trying to debug the real issue.

**Comment by tsatatwer** [comment]
@tiainen  thanks for the update and the efforts many windows javafx developers waiting the native image support and as you confirm the issue  [oracle/graal#2101](url) has been solved we are looking forward .

**Comment by jperedadnr** [comment]
Closing issue as Windows has been supported for a while now.
