### ISSUE TITLE
iOS 13 - text garbled

### ISSUE THREAD

**Issue by CedricGatay** [gluonhq/client-samples#24]
Hi, 

I am currently experiencing with Gluon to target mobile devices (specially iOS ones). And I discovered that text is unreadable under iOS 13, it works fine when running on iOS 12.

See screenshot attached:
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-22 at 08 47 39](https://user-images.githubusercontent.com/151195/67263528-ae738480-f4a8-11e9-8736-0a9e17fc4d3f.png)

I did not find any other issue related to this, but feel free to close it if I am not reporting it at the right place.

**Comment by sderosiaux** [comment]
I just tried, and I have the exact same issue (rendering a bit different but the same garbage), on macOS Catalina 10.15.

**Comment by johanvos** [comment]
@sderosiaux are you using the same pom as in the HelloFX sample?

**Comment by sderosiaux** [comment]
Yes, exactly the same. I just followed the exact same procedure, fresh install of GraalVM, env vars, git clone, mvn *.

**Comment by jperedadnr** [comment]
Issue filed: https://bugs.openjdk.java.net/browse/JDK-8234916, fix will be there soon.

In the meantime, using other fonts different than the system fonts should prevent this issue.

**Comment by jperedadnr** [comment]
Submitted PR to fix this issue: https://github.com/openjdk/jfx/pull/55

**Comment by jperedadnr** [comment]
Solved with JavaFX static 14-ea+gvm2
