### ISSUE TITLE
Bug in the HelloFXML Maven POM

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-samples#29]
There is a bug in the HelloFXML Maven POM.
Change the mainClassName from
`<mainClassName>hellofxml/hellofx.HelloFXML</mainClassName>`
to
`<mainClassName>hellofx.HelloFXML</mainClassName>`

**Comment by jperedadnr** [comment]
Thanks for reporting this issue. 

There is already a PR (#28) that will fix it for the current plugin version, and a proper fix has already been included in [Gluon Substrate](https://github.com/gluonhq/substrate/pull/115) and will allow using the module name in the main class name (though for native image it won't be relevant).

**Comment by jperedadnr** [comment]
Fixed with #28
