### ISSUE TITLE
HelloGluon: iOS blank screen upon launch

### ISSUE THREAD

**Issue by r-escu** [gluonhq/client-samples#39]
Using macOS 10.15.3 Beta (19D49f) to successfully build and run on iPad Air 2 both hellofx and hellofxml. When it comes too running hellogluon I get a blank screen upon application launch (no errors on output); it runs ok on macOS though. Any thoughts?

**Comment by jperedadnr** [comment]
HelloGluon requires some changes in both Gluon Mobile and Attach so the required reflection files are included. A new release is required, but should be out soon.

**Comment by jperedadnr** [comment]
It should be fixed with #40
