### ISSUE TITLE
HelloFX run fails: Graphics Device initialization failed for :  es2, sw

### ISSUE THREAD

**Issue by jolby** [gluonhq/client-samples#46]
HelloFX subdir builds with no errors (mvn clean client:build). Invoking mvn javafx:run runs fine and the window pops up. Invoking mvn client:run or running the build static binary directly produces the above error (full stacktrace at bottom of this message). I have included the link command output by the plugin. Let me know if I can provide any other information to assist debugging this issue.

HelloWorld subdir builds and runs fine (mvn clean client:build, mvn client:run). Also invoking the built static binary runs without error:
target/client/x86_64-linux/helloWorld
Hello World!!

- System Info:
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
$ dmesg | head -1
[    0.000000] Linux version 4.19.79-07511-ge32b3719f26b (chrome-bot@chromeos-ci-pre-try-us-central2-c-x32-13-iwzv) (Chromium OS 9.0_pre365631_p20190821-r21 clang version 9.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm-project 6b043f051836635a1e88da4d0464e6569bd7b625) (based on LLVM 9.0.0svn)) #1 SMP PREEMPT Mon Nov 18 17:41:41 PST 2019

- Link Command:
$ /bin/cat target/client/x86_64-linux/gvm/log/client-debug0.log
[Thu Jan 23 14:21:23 PST 2020][FINE] ==================== COMPILE TASK ====================
[Thu Jan 23 14:21:23 PST 2020][FINE] Processing JavaStatic dependencies at /home/jboehland/.gluon/substrate/javaStaticSdk/14-ea+5/linux-x86_64/labs-staticjdk/lib/static
[Thu Jan 23 14:21:23 PST 2020][FINE] Processing JavaFXStatic dependencies at /home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib
[Thu Jan 23 14:21:23 PST 2020][FINE] Process zip javaStaticSdk, target = linux-x86_64
[Thu Jan 23 14:21:23 PST 2020][FINE] Processing zip file: url = http://download2.gluonhq.com/substrate/staticjdk/labs-staticjdk-linux-x86_64-gvm-14-ea+5.zip, zip = /home/jboehland/.gluon/substrate/labs-staticjdk-linux-x86_64-gvm-14-ea+5.zip, subDir = javaStaticSdk, levels = [14-ea+5, linux-x86_64], md5 = javaStaticSdk-linux-x86_64.md5
[Thu Jan 23 14:21:24 PST 2020][FINE] Processing zip java done
[Thu Jan 23 14:21:24 PST 2020][FINE] Process zip javafxStaticSdk
[Thu Jan 23 14:21:24 PST 2020][FINE] Processing zip file: url = http://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-14-ea+gvm6-linux-x86_64-static.zip, zip = /home/jboehland/.gluon/substrate/openjfx-14-ea+gvm6-linux-x86_64-static.zip, subDir = javafxStaticSdk, levels = [14-ea+gvm6, linux-x86_64], md5 = javafxStaticSdk-linux-x86_64.md5
[Thu Jan 23 14:21:41 PST 2020][FINE] Process zip javafx done
[Thu Jan 23 14:21:41 PST 2020][FINE] Setup dependencies done
[Thu Jan 23 14:21:41 PST 2020][FINE] Extracting native libs to: /home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/client/x86_64-linux/gvm/lib
[Thu Jan 23 14:21:41 PST 2020][FINE] Looking for resource: /native/linux/launcher.c
[Thu Jan 23 14:21:41 PST 2020][FINE] PB Command for jar: jar cf /tmp/classes15170107816667043186/classes.jar -C /home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/classes .
[Thu Jan 23 14:21:41 PST 2020][FINE] Start process jar...
[Thu Jan 23 14:21:41 PST 2020][FINE] Result for jar: 0
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning for init build time files
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning /tmp/classes15170107816667043186/classes.jar
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning for reflection files
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning /tmp/classes15170107816667043186/classes.jar
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning for JNI files
[Thu Jan 23 14:21:41 PST 2020][FINE] Scanning /tmp/classes15170107816667043186/classes.jar
[Thu Jan 23 14:21:41 PST 2020][FINE] compile command: /usr/lib/jvm/graalvm/bin/native-image --report-unsupported-elements-at-runtime -Djdk.internal.lambda.eagerlyInitialize=false -H:+ExitAfterRelocatableImageWrite -H:TempDirectory=/home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/client/x86_64-linux/gvm/tmp -H:+SharedLibrary -H:+AddAllCharsets -H:EnableURLProtocols=http,https -H:ReflectionConfigurationFiles=/home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/client/x86_64-linux/gvm/reflectionconfig-x86_64-linux.json -H:JNIConfigurationFiles=/home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/client/x86_64-linux/gvm/jniconfig-x86_64-linux.json -H:+PrintAnalysisCallTree -H:ResourceConfigurationFiles=/home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/client/x86_64-linux/gvm/resourceconfig-x86_64-linux.json -H:Log=registerResource: -H:IncludeResourceBundles=com/sun/javafx/scene/control/skin/resources/controls,com.sun.javafx.tk.quantum.QuantumMessagesBundle -Dsvm.platform=org.graalvm.nativeimage.Platform$LINUX_AMD64 -cp /home/jboehland/repos/java/gluon/client-samples/Maven/HelloFX/target/classes:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-base.jar:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-base.jar:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-controls.jar:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-controls.jar:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-graphics.jar:/home/jboehland/.gluon/substrate/javafxStaticSdk/14-ea+gvm6/linux-x86_64/sdk/lib/javafx-graphics.jar hellofx.HelloFX
[Thu Jan 23 14:25:08 PST 2020][FINE] ==================== RUN TASK ====================

- Full Stacktrace:
$ target/client/x86_64-linux/hellofx
Main
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 3 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by jperedadnr** [comment]
If you are running in a virtualized environment where hw is not available, JavaFX defaults to sw rendering. That is done out of the box when you run javafx:run. 

However, with native image, the client plugin doesn't include sw by default, as it has some influence in memory footprint.

With the latest plugin 0.1.14 you can try setting:
```
<enableSWRendering>true</enableSWRendering>
```

Run again and see if that helps.

**Comment by jolby** [comment]
Hello @jperedadnr,
Thank you, I was able to get the static binary to run after setting the enableSWRendering property.
