### ISSUE TITLE
HelloGluon build fails on mac

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/client-samples#47]
I followed the various steps in the guide but I get this error:

Mac-xxx:HelloGluon Utente$ mvn clean client:build
[INFO] Scanning for projects...
[INFO] --------------------< com.gluonhq.hello:hellogluon >--------------------
[INFO] Building hellogluon 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hellogluon ---
[INFO] --------------------< com.gluonhq.hello:hellogluon >--------------------
[INFO] Building hellogluon 1.0-SNAPSHOT
[INFO] --- client-maven-plugin:0.1.14:build (default-cli) @ hellogluon ---
[INFO] --------------------< com.gluonhq.hello:hellogluon >--------------------
[INFO] Building hellogluon 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] --- client-maven-plugin:0.1.14:compile (default-cli) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/xxx/client-samples-master/Maven/HelloGluon/target/classes
We will now compile your code for arm64-apple-ios. This may take some time.
Build on Server(pid: 49502, port: 51590)*
...
Fatal error: org.graalvm.compiler.debug.GraalError: java.io.IOException: Cannot run program "llvm-link" (in directory "/Users/xxx/client-samples-master/Maven/HelloGluon/target/client/arm64-ios/gvm/tmp/SVM-1580114083832/llvm"): error=2, No such file or directory
	at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.llvmLink(LLVMNativeImageCodeCache.java:555)
	at com.oracle.svm.core.graal.llvm.LLVMNativeImageCodeCache.lambda$createBitcodeBatches$8(LLVMNativeImageCodeCache.java:433)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)

what to do?

**Comment by jperedadnr** [comment]
You are building for iOS.
Check https://github.com/gluonhq/client-samples#building-and-running-the-samples-on-ios

**Comment by websystemtechnology** [comment]
Yes, I have already followed the guide and the procedure for iOS, but I always get the error as indicated in the first message.

**Comment by jperedadnr** [comment]
But have you installed LLVM and added it to the path? Make sure that is the case (i.e. run `echo $PATH` and verify it)?

**Comment by websystemtechnology** [comment]
Yes, I've installed everything. I've only one doubt about the path. 
Is it possible to see an example of the path?

**Comment by websystemtechnology** [comment]
I followed the guide, and I created a test IPA and everything is ok.
How do I specify a different Default-nfo.plist, without each time the build or package overwrites it?

**Comment by odbuser2** [comment]
**Copy** 
target/client/arm64-ios/gensrc/*
**to**
src/

**Now you'll  have the following to customize**
src/Default-Info.plist
src/assets/*

I just guessed... and it works.

**Comment by websystemtechnology** [comment]
Sorry I don't understand: "copy ... to ...".
Do I have to copy the whole folder to scr?

**Comment by jperedadnr** [comment]
If you don't have `src/ios` with the plist and assets, the plugin creates target/client/$arch-$os/gensrc. The plugin prints a message while linking, but probably it is not very visible:
```
Default iOS resources generated in /path/to/target/client/$arch-$OS/gensrc.
Consider copying them to /path/to/src/ios before performing any modification
```

You need to move the content from gensrc to src/ios, so you have `src/ios/Default-Info.plist`, and `src/ios/assets/...

**Comment by websystemtechnology** [comment]
Sorry, I'm trying to compile using the ios-sim target for the simulator, but I get this error:
"Error downloading from http://download2.gluonhq.com/substrate/staticjdk/labs-staticjdk-ios-x86_64-gvm-14-ea+5.zip"
What should I do?

**Comment by websystemtechnology** [comment]
Sorry, do you know if it is possible to set the ios certificate of the provisioning profile registered on pom.xml? Thanks for the reply.

**Comment by websystemtechnology** [comment]
Sorry, I have a problem with iPhoneX. The apps on the iphoneX are seen in reduced screen because of the notch, how can i solve this?
