### ISSUE TITLE
Android installation Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by bezvaapp** [gluonhq/client-samples#72]
I built HelloGluon for Android on
Ubuntu 19.10 on VirtualBox on Windows 10 on Intel CPU
for Android 9

The Android apk was created successfully but when I do the installation to the connected Android 9 device using

mvn client:install

I get the error. Apparently there is a mismatch between the native libraries and the target architecture. 

Any suggestion as to how to solve this please? Thank you.

`Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

**Comment by bezvaapp** [comment]
Apparently it is because my device has architecture 
armeabi-v7a,armeabi

and the substrate builds for
arm64-v8a

Is it technically possible to build for armeabi-v7a,armeabi if I change the target in the substrate code or is it not supported at all?

**Comment by abhinayagarwal** [comment]
Hi @bezvaapp ,

I am closing this issue. If you want support for armeabi-v7a, armeabi devices, please feel free to open a ticket in [gluonhq/substrate](https://github.com/gluonhq/substrate).
