### ISSUE TITLE
FXML and JavaScript examples

### ISSUE THREAD

**Issue by XakepSDK** [gluonhq/client-samples#74]
Is this possible to use JavaScript in FXML? I would appreciate for FXML + JavaScript examples

**Comment by abhinayagarwal** [comment]
Hi @XakepSDK ,

Please refer to "[Introduction to FXML](https://docs.oracle.com/javase/8/javafx/api/javafx/fxml/doc-files/introduction_to_fxml.html)" guide for a better understanding on FXML.

You can use CSS, but JS is not ~supported~ required as the logic can be handled in Java.

**Comment by XakepSDK** [comment]
Is this GraalVM limitation?

**Comment by abhinayagarwal** [comment]
FXML has nothing to do with GraalVM. FXML uses XML to create UI views for JavaFX.

If you want to check out a mobile app built on JavaFX, leveraging GraalVM's multi-lanuage stack, please check https://github.com/lazar-mitrovic/GraalREPL

**Comment by XakepSDK** [comment]
Well, it's probably misunderstanding. We have some heavy JavaFX app, that uses FXML and JavaScript. We want to use GraalVM to make single executable. Parts, that don't use JavaScript, work well, but parts where JavaScript is used, do not work, because it can't find JavaScript engine.
And, as far i know, GraalVM supports JS in native-image, if argument `--launguage:js` present.
I tried to compile it with this argument added, but it didn't work.

**Comment by abhinayagarwal** [comment]
Can you give a short example on how you are leveraging JavaScript in your JavaFX app?
