### ISSUE TITLE
error C2371: 'size_t': redefinition; different basic types

### ISSUE THREAD

**Issue by tsatatwer** [gluonhq/client-samples#78]
While compiling in windows 10 64bit using VC 2019 I get this error :
`launcher.c
C:\Program Files (x86)\Microsoft Visual Studio\VC98\include\stdio.h(70): error C2371: 'size_t': redefinition; different basic types
launcher.c: note: see declaration of 'size_t'
`
I set cl.exe 64bit in windows PATH.....
The log:

cl -c -DSUBSTRATE /MD /D_UNICODE /DUNICODE /DWIN32 /D_WINDOWS -ID:\Javafx Native\client-samples-master\Maven\HelloFXML\target\client\x86_64-windows\gvm\hellofxml launcher.c

Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

launcher.c
C:\Program Files (x86)\Microsoft Visual Studio\VC98\include\stdio.h(70): error C2371: 'size_t': redefinition; different basic types
launcher.c: note: see declaration of 'size_t'`

**Comment by tiainen** [comment]
I see you closed this issue already. Can you explain what you did to resolve it? That way, others that get confronted with this issue in the future can find the answer here.
