### ISSUE TITLE
Resource file in json format not found after client-maven-plugin build

### ISSUE THREAD

**Issue by piosystems** [gluonhq/client-samples#80]
I added a _settings.json_ file to my resources folder and I can access it when I run my maven project using the basic _mvn javafx:run_. I also successfully built the executable file using _client-maven-plugin version 0.1.24_. Unfortunately, when I run the built executable file, I always get the error message _settings.json (The system cannot find the file specified)_. The code snippet is very simple:

try{
   Reader reader = new FileReader(App.class.getResource("/settings.json").getFile());
   ...
}catch(IOException e){
   System.out.println(e.getMessage());
}

I just can't see where I have gotten anything wrong. Besides, it works with mvn javafx:run. Is this a bug or is there an extra configuration missing?

**Comment by tiainen** [comment]
You are converting a resource URL to a File. It works locally, because the file exists in your classpath (check the folder `target/classes` and you'll see that the `settings.json` file is there). When you would run this application with only the jar file on the classpath (which you can get by running `mvn package`), you'll notice it won't work either.

Try using `Class.getResourceAsStream()` instead of `Class.getResource()`

    try (Reader reader = new InputStreamReader(App.class.getResourceAsStream("/settings.json"))) {
        ...
    } catch (IOException e) {
        System.out.println(e.getMessage());
    }

**Comment by gailasgteach** [comment]
Not sure about .json files, but for .properties files, I had to include them in the pom.xml resource list:

<plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>${client.plugin.version}</version>
                <configuration>
                    <target>${clientTarget}</target>
                    <attachList>
                        <list>display</list>
                        <list>lifecycle</list>
                        <list>statusbar</list>
                        <list>storage</list>
                        <list>util</list>
                    </attachList> 
                    <resourcesList>
                         <list>settings.json</list>
                    </resourcesList> 
                    <verbose>false</verbose>
                    <mainClass>${mainClassName}</mainClass>
                </configuration>
            </plugin>

**Comment by tiainen** [comment]
*.json files are included by default.

**Comment by piosystems** [comment]
@tiainen, your suggestion worked. i.e. use "Class.getResourceAsStream() instead of Class.getResource()". Thanks
