### ISSUE TITLE
Run built native code without cli showing

### ISSUE THREAD

**Issue by piosystems** [gluonhq/client-samples#81]
Is there an option to run a built native program (on Windows, Mac or Linux) without a command line interface displayed along with the running program's GUI window?

**Comment by odbuser2** [comment]
I believe this is going to be supported in the maven plugin using the goal client:package.
The docs say "At the moment, this goal is only supported for iOS and Android"
https://docs.gluonhq.com/client/#_client_package

Frustrating.

**Comment by piosystems** [comment]
Any roadmap published online somewhere?

**Comment by thinkiny** [comment]
desire for this

**Comment by tiainen** [comment]
Tracked by https://github.com/gluonhq/substrate/issues/638

**Comment by thinkiny** [comment]
this is for windows. macos may need use app boudle manually

**Comment by tiainen** [comment]
Fixed in client-maven-plugin 0.1.27.

**Comment by piosystems** [comment]
I am now using client-maven-plugin 0.1.27 but still encountered problems  when I run mvn clean client:build:
1. On Windows 10, I get a series of link errors from Microsoft (R) Incremental Linker Version 14.25.28614.0. The error message includes these lines:
error LNK2001: unresolved external symbol StrictMath_acos
error LNK2001: unresolved external symbol StrictMath_asin
 error LNK2001: unresolved external symbol StrictMath_atan2
error LNK2001: unresolved external symbol StrictMath_cbrt
 error LNK2001: unresolved external symbol StrictMath_hypot

I am using graalvm-ce-java11-20.2.0-dev which I downloaded on the 16th of May.

2. On Mac, the build was successful but a terminal window still opens when I directly run the executable file that was generated by the build.

Kindly advise.

**Comment by piosystems** [comment]
> I am now using client-maven-plugin 0.1.27 but still encountered problems when I run mvn clean client:build:
> 
> 1. On Windows 10, I get a series of link errors from Microsoft (R) Incremental Linker Version 14.25.28614.0. The error message includes these lines:
>    error LNK2001: unresolved external symbol StrictMath_acos
>    error LNK2001: unresolved external symbol StrictMath_asin
>    error LNK2001: unresolved external symbol StrictMath_atan2
>    error LNK2001: unresolved external symbol StrictMath_cbrt
>    error LNK2001: unresolved external symbol StrictMath_hypot
> 
> I am using graalvm-ce-java11-20.2.0-dev which I downloaded on the 16th of May.
> 
> 1. On Mac, the build was successful but a terminal window still opens when I directly run the executable file that was generated by the build.
> 
> Kindly advise.

The problem disappeared after updating the graalvm-ce-java11-20.2.0-dev to the latest
